# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: 每周自动爬取QA信息

on:
  schedule:
  - cron: "0 8 * * 3"
  workflow_dispatch:

# permissions:
#   contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: 安装 Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
        
    - name: 安装依赖包
      run: |
        python -m pip install --upgrade pip
        pip install requests
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        
    - name: 爬取QA信息
      run: python crawler.py
        
    - name : 同步爬取结果至github
      uses: actions/upload-artifact@v3
      with:
        name: 爬取结果
        path: |
          ${{ github.workspace }}/articles/
          ${{ github.workspace }}/cuts/
          ${{ github.workspace }}/articles_list.json
          ${{ github.workspace }}/output.json
        
